- name: cart
  hosts: cart
  become: yes
  tasks:
  - name: disable old nodejs and enabled node js
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install nodejs
    amsible.builtin.dnf:
      name: nodejs
      state: present

  - name: create roboshop user
    ansible.builtin.user:
      name : roboshop

  - name: Recursively remove app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download cart application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp

  - name: ectract cart application
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
      chidr: /app

  - name: copy cart service
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: deamon reload and start
    ansible.builtin.systemd_service:
      deamon_reload: true

  - name: start and enable cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes